# Generated by Django 3.0.8 on 2020-08-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200803_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('RECEPTIONIST', 'Receptionist')], max_length=12, null=True),
        ),
    ]
