# Generated by Django 3.0.8 on 2020-08-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200805_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
