# Generated by Django 3.0.8 on 2020-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='kind',
            field=models.CharField(blank=True, choices=[('N', 'New Patient'), ('F', 'Follow-up')], max_length=1, null=True),
        ),
    ]
